# Generated by Django 3.1 on 2020-09-09 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
