# Generated by Django 3.1 on 2020-09-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='customer',
        ),
    ]
