# Generated by Django 3.1 on 2020-09-20 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200918_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fixed_amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('percent_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
