# Generated by Django 3.1 on 2020-09-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200920_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percent_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
