# Generated by Django 3.1.4 on 2020-12-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_coupon_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
