# Generated by Django 3.1 on 2020-08-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_variation_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.png', upload_to='item_pics'),
        ),
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ImageField(default='default.png', upload_to='item_variation_pics'),
        ),
    ]
