# Generated by Django 3.1 on 2020-08-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20200821_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='image',
        ),
        migrations.CreateModel(
            name='VariationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='regular', max_length=100)),
                ('image', models.ImageField(default='default_variation.png', upload_to='item_variation_pics')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.variation')),
            ],
        ),
    ]
