# Generated by Django 3.1 on 2020-08-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20200823_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationimage',
            name='alias',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='variationimage',
            name='name',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
