# Generated by Django 3.1 on 2020-09-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
