# Generated by Django 3.1 on 2020-10-08 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
