# Generated by Django 3.1 on 2020-10-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_order_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
