# Generated by Django 3.1 on 2020-10-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_orderitem_ordered_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name_plural': 'Order Statuses'},
        ),
    ]
