# Generated by Django 3.1 on 2020-10-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_label',
            field=models.CharField(choices=[('NW', 'New'), ('SD', 'Sold'), ('BS', 'Bestseller'), ('SL', 'Sale')], default='NW', max_length=2),
        ),
        migrations.AddField(
            model_name='variation',
            name='item_label',
            field=models.CharField(choices=[('NW', 'New'), ('SD', 'Sold'), ('BS', 'Bestseller'), ('SL', 'Sale')], default='NW', max_length=2),
            preserve_default=False,
        ),
    ]
