# Generated by Django 3.1 on 2020-11-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201006_1437'),
        ('items', '0004_itemcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemComment',
            new_name='ItemReview',
        ),
    ]
