# Generated by Django 3.1 on 2020-11-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20201113_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreview',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
