# Generated by Django 3.1 on 2020-11-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201006_1437'),
        ('items', '0008_auto_20201119_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreview',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
    ]
