# Generated by Django 3.1.4 on 2021-01-04 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20201124_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationimage',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='variationimage',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
